export const initialShipments = [
  {
    id: "SMP-1001",
    buyerName: "Artisan Roaster Co.",
    contactEmail: "purchasing@artisanroaster.de",
    country: "Germany",
    region: "Europe",
    coffeeType: "Geisha Special Reserve - Batch A",
    weightKg: 2.5,
    waybill: "DHL-984210382",
    dispatchDate: "2026-07-15",
    estimatedDelivery: "2026-07-19",
    deliveredDate: "2026-07-19",
    dhlStatus: "Delivered",
    buyerStatus: "Confirmed",
    lastPingDate: "2026-07-20",
    dhlTimeline: [
      {
        date: "2026-07-15 09:30",
        location: "Nairobi Hub",
        status: "Shipment Picked Up",
      },
      {
        date: "2026-07-16 14:10",
        location: "Leipzig Hub",
        status: "Processed at Sort Facility",
      },
      {
        date: "2026-07-19 10:15",
        location: "Berlin Facility",
        status: "Delivered - Signed by Hans M.",
      },
    ],
    emailLogs: [
      {
        date: "2026-07-15 10:00",
        sender: "System",
        type: "Dispatch Notification",
        preview: "Waybill DHL-984210382 dispatched via DHL Express.",
      },
      {
        date: "2026-07-20 08:30",
        sender: "purchasing@artisanroaster.de",
        type: "Buyer Reply",
        preview: "Sample received! The Geisha profile exceeds expectations.",
      },
    ],
  },
  {
    id: "SMP-1002",
    buyerName: "Tokyo Bean Crafters",
    contactEmail: "kenji@tokyobean.jp",
    country: "Japan",
    region: "Asia-Pacific",
    coffeeType: "SL28 Washed Process",
    weightKg: 5.0,
    waybill: "DHL-473920193",
    dispatchDate: "2026-07-18",
    estimatedDelivery: "2026-07-22",
    deliveredDate: "2026-07-22",
    dhlStatus: "Delivered",
    buyerStatus: "Pending",
    lastPingDate: "2026-07-22",
    dhlTimeline: [
      {
        date: "2026-07-18 11:00",
        location: "Nairobi Hub",
        status: "Shipment Picked Up",
      },
      {
        date: "2026-07-20 03:40",
        location: "Hong Kong Hub",
        status: "In Transit",
      },
      {
        date: "2026-07-22 14:20",
        location: "Tokyo Gateway",
        status: "Delivered - Left at Reception",
      },
    ],
    emailLogs: [
      {
        date: "2026-07-18 11:15",
        sender: "System",
        type: "Dispatch Notification",
        preview: "Waybill DHL-473920193 dispatched via DHL Express.",
      },
      {
        date: "2026-07-22 15:00",
        sender: "System (Auto-Ping)",
        type: "Receipt Inquiry",
        preview: "Automated ping sent asking for receipt confirmation.",
      },
    ],
  },
  {
    id: "SMP-1003",
    buyerName: "Nordic Wave Coffee",
    contactEmail: "import@nordicwave.se",
    country: "Sweden",
    region: "Europe",
    coffeeType: "SL34 Natural Honey",
    weightKg: 3.0,
    waybill: "DHL-381920384",
    dispatchDate: "2026-07-12",
    estimatedDelivery: "2026-07-16",
    deliveredDate: null,
    dhlStatus: "Delayed",
    buyerStatus: "Unconfirmed",
    lastPingDate: "2026-07-18",
    dhlTimeline: [
      {
        date: "2026-07-12 10:00",
        location: "Nairobi Hub",
        status: "Shipment Picked Up",
      },
      {
        date: "2026-07-14 18:20",
        location: "Frankfurt Hub",
        status: "Customs Clearance Delay",
      },
      {
        date: "2026-07-16 09:00",
        location: "Frankfurt Hub",
        status: "Held for Clearance Inspection",
      },
    ],
    emailLogs: [
      {
        date: "2026-07-12 10:15",
        sender: "System",
        type: "Dispatch Notification",
        preview: "Waybill DHL-381920384 dispatched.",
      },
      {
        date: "2026-07-17 09:00",
        sender: "import@nordicwave.se",
        type: "Buyer Inquiry",
        preview: "Any update on customs clearance? DHL says held.",
      },
    ],
  },
  {
    id: "SMP-1004",
    buyerName: "Pacific Coast Imports",
    contactEmail: "sourcing@pacificcoast.com",
    country: "United States",
    region: "North America",
    coffeeType: "Peaberry Special Roast",
    weightKg: 2.0,
    waybill: "DHL-883920112",
    dispatchDate: "2026-07-20",
    estimatedDelivery: "2026-07-24",
    deliveredDate: null,
    dhlStatus: "In Transit",
    buyerStatus: "Pending",
    lastPingDate: null,
    dhlTimeline: [
      {
        date: "2026-07-20 14:00",
        location: "Nairobi Hub",
        status: "Shipment Picked Up",
      },
      {
        date: "2026-07-21 22:15",
        location: "Cincinnati Gateway",
        status: "Arrived at Sort Facility",
      },
    ],
    emailLogs: [
      {
        date: "2026-07-20 14:30",
        sender: "System",
        type: "Dispatch Notification",
        preview: "Waybill DHL-883920112 dispatched via DHL Express.",
      },
    ],
  },
  {
    id: "SMP-1005",
    buyerName: "Melbourne Craft Roasters",
    contactEmail: "orders@melbournecraft.au",
    country: "Australia",
    region: "Asia-Pacific",
    coffeeType: "Geisha Special Reserve - Batch B",
    weightKg: 1.5,
    waybill: "DHL-102938475",
    dispatchDate: "2026-07-10",
    estimatedDelivery: "2026-07-15",
    deliveredDate: "2026-07-15",
    dhlStatus: "Delivered",
    buyerStatus: "Confirmed",
    lastPingDate: "2026-07-16",
    dhlTimeline: [
      {
        date: "2026-07-10 08:30",
        location: "Nairobi Hub",
        status: "Shipment Picked Up",
      },
      {
        date: "2026-07-12 16:45",
        location: "Singapore Hub",
        status: "Processed at Sort Facility",
      },
      {
        date: "2026-07-15 11:10",
        location: "Melbourne Airport",
        status: "Delivered - Signed by Sarah L.",
      },
    ],
    emailLogs: [
      {
        date: "2026-07-10 09:00",
        sender: "System",
        type: "Dispatch Notification",
        preview: "Waybill DHL-102938475 dispatched.",
      },
      {
        date: "2026-07-16 10:20",
        sender: "orders@melbournecraft.au",
        type: "Buyer Reply",
        preview:
          "Sample arrived on time. Cupping session scheduled for Friday.",
      },
    ],
  },
];
